# -*- coding: utf-8 -*-
"""AI_image_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qA4kHqsOlL23K1cwWZFZ6w4jOa-H9mVN
"""

# ============================================
# 1단계: 라이브러리 설치
# ============================================
!pip install diffusers accelerate torch gradio huggingface_hub
!pip install --upgrade torchao peft

# ⚠️ 여기까지 실행한 다음 반드시 런타임 재시작!
# 메뉴 → 런타임 → 세션 다시 시작

from huggingface_hub import list_repo_files

# 가능한 이름들 시도
names = [
    "CyberHarem/silverwolf_starrail",
    "CyberHarem/silverwolf_honkaistarrail",
    "CyberHarem/silver_wolf_starrail"
]

for name in names:
    try:
        files = list(list_repo_files(name))
        print(f"✅ 찾음: {name}")
        print(files[:3])
        break
    except:
        print(f"❌ 없음: {name}")

import torch
import gradio as gr
from diffusers import StableDiffusionPipeline
from huggingface_hub import hf_hub_download, list_repo_files

pipe = StableDiffusionPipeline.from_pretrained(
    "Linaqruf/anything-v3-1",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")
pipe.safety_checker = None
pipe.requires_safety_checker = False

# 수채화 LoRA 자동 로드
style_files = list_repo_files("SydigiAI/WaterColorStyle-loRA")
style_safetensors = [f for f in style_files if f.endswith(".safetensors")]
style_lora_path = hf_hub_download(
    repo_id="SydigiAI/WaterColorStyle-loRA",
    filename=style_safetensors[0]
)
pipe.load_lora_weights(style_lora_path, adapter_name="style")
print("✅ 스타일 LoRA 로드 완료")

current_character = {"name": None}

def load_character_lora(character_name, game):
    if character_name == current_character["name"]:
        return f"이미 {character_name} 로드됨"

    # 게임에 따라 repo 변경
    if game == "스타레일":
        repo_id = f"CyberHarem/{character_name}_starrail"
        file_suffix = f"{character_name}_starrail.safetensors"
    else:
        repo_id = f"CyberHarem/{character_name}_arknights"
        file_suffix = f"{character_name}_arknights.safetensors"

    try:
        files = list_repo_files(repo_id)
        safetensors = [f for f in files if f.endswith(file_suffix)]

        if not safetensors:
            return f"❌ {character_name} LoRA 못 찾음"

        safetensors.sort(
            key=lambda x: int(x.split("/")[0]) if x.split("/")[0].isdigit() else 0,
            reverse=True
        )
        target_file = safetensors[0]

        lora_path = hf_hub_download(repo_id=repo_id, filename=target_file)

        if current_character["name"] is not None:
            pipe.delete_adapters("character")

        pipe.load_lora_weights(lora_path, adapter_name="character")
        current_character["name"] = character_name

        return f"✅ {character_name} 로드 완료"
    except Exception as e:
        return f"❌ 오류: {str(e)}"

def generate(character, game, prompt, negative_prompt, steps, char_scale, style_scale, cfg, resolution):
    status = load_character_lora(character, game)
    pipe.set_adapters(["character", "style"], adapter_weights=[char_scale, style_scale])

    full_prompt = f"{character}_starrail, Sora WaterColor, {prompt}" if game == "스타레일" \
        else f"{character}_arknights, Sora WaterColor, {prompt}"

    image = pipe(
        full_prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=int(steps),
        guidance_scale=cfg,
        width=int(resolution),
        height=int(resolution)
    ).images[0]
    return image, status

demo = gr.Interface(
    fn=generate,
    inputs=[
        gr.Textbox(label="캐릭터 이름", value="silver_wolf"),
        gr.Radio(["스타레일", "명일방주"], label="게임 선택", value="스타레일"),
        gr.Textbox(label="프롬프트", value="upper body, 1girl, illustration, soft colors, detailed face"),
        gr.Textbox(label="네거티브 프롬프트", value="worst quality, low quality, bad anatomy, bad hands, lowres, deformed face"),
        gr.Slider(10, 40, value=25, label="생성 단계"),
        gr.Slider(0.0, 1.0, value=0.7, step=0.1, label="캐릭터 LoRA 강도"),
        gr.Slider(0.0, 1.0, value=0.3, step=0.1, label="수채화 LoRA 강도"),
        gr.Slider(1.0, 15.0, value=6.0, step=0.5, label="CFG"),
        gr.Slider(512, 1024, value=768, step=64, label="해상도")
    ],
    outputs=[
        gr.Image(label="결과"),
        gr.Textbox(label="LoRA 상태")
    ],
    title="스타레일 / 명일방주 캐릭터 생성기"
)

demo.launch()

# 새 셀에서 테스트
from huggingface_hub import list_repo_files
files = list(list_repo_files("CyberHarem/silver_wolf_starrail"))
print(files[:5])

files = list(list_repo_files("CyberHarem/silver_wolf_starrail"))
safetensors = [f for f in files if f.endswith(".safetensors")]
print(safetensors)

from huggingface_hub import hf_hub_download

repo_id = "CyberHarem/silver_wolf_starrail"
target = "1000/silver_wolf_starrail.safetensors"

try:
    lora_path = hf_hub_download(repo_id=repo_id, filename=target)
    print("다운로드 성공:", lora_path)

    pipe.load_lora_weights(lora_path, adapter_name="character")
    print("✅ LoRA 로드 성공!")
except Exception as e:
    print("❌ 오류:", e)

target = "1000/silver_wolf_starrail_raw.safetensors"

try:
    lora_path = hf_hub_download(repo_id=repo_id, filename=target)
    print("다운로드 성공:", lora_path)

    pipe.load_lora_weights(lora_path, adapter_name="character")
    print("✅ LoRA 로드 성공!")
except Exception as e:
    print("❌ 오류:", e)

import torch
import gradio as gr
from diffusers import StableDiffusionPipeline
from huggingface_hub import hf_hub_download, list_repo_files

pipe = StableDiffusionPipeline.from_pretrained(
    "Linaqruf/anything-v3-1",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")
pipe.safety_checker = None
pipe.requires_safety_checker = False

# 수채화 LoRA 자동 로드
style_files = list_repo_files("SydigiAI/WaterColorStyle-loRA")
style_safetensors = [f for f in style_files if f.endswith(".safetensors")]
style_lora_path = hf_hub_download(
    repo_id="SydigiAI/WaterColorStyle-loRA",
    filename=style_safetensors[0]
)
pipe.load_lora_weights(style_lora_path, adapter_name="style")
print("✅ 스타일 LoRA 로드 완료")

current_character = {"name": None}

def load_character_lora(character_name, game):
    if character_name == current_character["name"]:
        return f"이미 {character_name} 로드됨"

    if game == "스타레일":
        repo_id = f"CyberHarem/{character_name}_starrail"
        file_suffix = f"{character_name}_starrail_raw.safetensors"  # _raw 버전
    else:
        repo_id = f"CyberHarem/{character_name}_arknights"
        file_suffix = f"{character_name}_arknights.safetensors"

    try:
        files = list_repo_files(repo_id)
        safetensors = [f for f in files if f.endswith(file_suffix)]

        if not safetensors:
            return f"❌ {character_name} LoRA 못 찾음"

        safetensors.sort(
            key=lambda x: int(x.split("/")[0]) if x.split("/")[0].isdigit() else 0,
            reverse=True
        )
        target_file = safetensors[0]

        lora_path = hf_hub_download(repo_id=repo_id, filename=target_file)

        if current_character["name"] is not None:
            pipe.delete_adapters("character")

        pipe.load_lora_weights(lora_path, adapter_name="character")
        current_character["name"] = character_name

        return f"✅ {character_name} 로드 완료"
    except Exception as e:
        return f"❌ 오류: {str(e)}"

def generate(character, game, prompt, negative_prompt, steps, char_scale, style_scale, cfg, resolution):
    status = load_character_lora(character, game)
    pipe.set_adapters(["character", "style"], adapter_weights=[char_scale, style_scale])

    trigger = f"{character}_starrail" if game == "스타레일" else f"{character}_arknights"
    full_prompt = f"{trigger}, Sora WaterColor, {prompt}"

    image = pipe(
        full_prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=int(steps),
        guidance_scale=cfg,
        width=int(resolution),
        height=int(resolution)
    ).images[0]
    return image, status

demo = gr.Interface(
    fn=generate,
    inputs=[
        gr.Textbox(label="캐릭터 이름", value="silver_wolf"),
        gr.Radio(["스타레일", "명일방주"], label="게임 선택", value="스타레일"),
        gr.Textbox(label="프롬프트", value="upper body, 1girl, illustration, soft colors, detailed face, beautiful detailed eyes, looking at viewer"),
        gr.Textbox(label="네거티브 프롬프트", value="worst quality, low quality, bad anatomy, bad hands, lowres, deformed face"),
        gr.Slider(10, 40, value=25, label="생성 단계"),
        gr.Slider(0.0, 1.0, value=0.7, step=0.1, label="캐릭터 LoRA 강도"),
        gr.Slider(0.0, 1.0, value=0.3, step=0.1, label="수채화 LoRA 강도"),
        gr.Slider(1.0, 15.0, value=6.0, step=0.5, label="CFG"),
        gr.Slider(512, 1024, value=768, step=64, label="해상도")
    ],
    outputs=[
        gr.Image(label="결과"),
        gr.Textbox(label="LoRA 상태")
    ],
    title="스타레일 / 명일방주 캐릭터 생성기"
)

demo.launch()